spring:
  application:
    name: spring-boot-kotlin-tutorial
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
jwt:
  secret: SecretKeySecretKeySecretKeySecretKeySecretKey
  refresh-secret: RefreshSecretKeyRefreshSecretKeyRefreshSecretKey
  expire-min: 60
  refresh-expire-min: 600
blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow
